/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutPlanosRouteImport } from './routes/_layout.planos'
import { Route as LayoutBuscarRouteImport } from './routes/_layout.buscar'
import { Route as LayoutBibliotecaRouteImport } from './routes/_layout.biblioteca'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlanosRoute = LayoutPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuscarRoute = LayoutBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBibliotecaRoute = LayoutBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/biblioteca': typeof LayoutBibliotecaRoute
  '/buscar': typeof LayoutBuscarRoute
  '/planos': typeof LayoutPlanosRoute
}
export interface FileRoutesByTo {
  '/biblioteca': typeof LayoutBibliotecaRoute
  '/buscar': typeof LayoutBuscarRoute
  '/planos': typeof LayoutPlanosRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/biblioteca': typeof LayoutBibliotecaRoute
  '/_layout/buscar': typeof LayoutBuscarRoute
  '/_layout/planos': typeof LayoutPlanosRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/biblioteca' | '/buscar' | '/planos'
  fileRoutesByTo: FileRoutesByTo
  to: '/biblioteca' | '/buscar' | '/planos' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/biblioteca'
    | '/_layout/buscar'
    | '/_layout/planos'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/planos': {
      id: '/_layout/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof LayoutPlanosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/buscar': {
      id: '/_layout/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof LayoutBuscarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/biblioteca': {
      id: '/_layout/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof LayoutBibliotecaRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBibliotecaRoute: typeof LayoutBibliotecaRoute
  LayoutBuscarRoute: typeof LayoutBuscarRoute
  LayoutPlanosRoute: typeof LayoutPlanosRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBibliotecaRoute: LayoutBibliotecaRoute,
  LayoutBuscarRoute: LayoutBuscarRoute,
  LayoutPlanosRoute: LayoutPlanosRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
